services:
  app:
    build: .
    environment:
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: host.docker.internal
      TYPEORM_USERNAME: hkadmin
      TYPEORM_PASSWORD: supersecret
      TYPEORM_DATABASE: hkadmin
      TYPEORM_PORT: 3306
      TYPEORM_SYNCHRONIZE: 'true'
      TYPEORM_LOGGING: 'false'
      TYPEORM_ENTITIES: dist/**/*.entity.js
    ports:
      - 3000:3000
  db:
    image: mysql:5
    restart: always
    volumes:
      - hkadmin-db:/var/lib/mysql
      - ./script/:/script
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: hkadmin
      MYSQL_PASSWORD: supersecret
      MYSQL_DATABASE: hkadmin

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
     - 8888:80
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3306
      PMA_USER: hkadmin
      PMA_PASSWORD: supersecret

volumes:
  hkadmin-db:
