services:
  test-db:
    image: mysql:5
    restart: always
    volumes:
      - hkadmin-test-db:/var/lib/mysql
      - ./script/:/script
    ports:
      - ${TEST_DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: hkadmin
      MYSQL_PASSWORD: supersecret
      MYSQL_DATABASE: hkadmin
volumes:
  hkadmin-test-db:
